name: Generate Files JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate files.json
      run: |
        mkdir -p data
        echo '{ "files": [' > data/files.json
        for file in download/*; do
          if [ "$file" != "download/*" ]; then
            echo "\"$(basename "$file")\"," >> data/files.json
          fi
        done
        sed -i '$ s/.$//' data/files.json
        echo ']}' >> data/files.json

    - name: Commit files.json
      env:
        MY_PAT: ${{ secrets.MY_PAT }} # Use the custom secret name here
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add data/files.json
        git commit -m 'Generate files.json' || echo "No changes to commit"
        git push https://x-access-token:${MY_PAT}@github.com/${{ github.repository }} HEAD:refs/heads/main
